const LEVEL1 = new Level(
    [
        new Zombie(),
        new Zombie(),
        new Zombie(),
    ],
    [
        new Monster(),
        new Monster(),
        new Monster(),
        new Monster(),
        new Monster(),
    ],
    [
        new Cloud()
    ],
    [
        new BackgroundObject('../img2/5_background/layers/cemetary_background_night_02.png', -1706, 0),
        new BackgroundObject('../img2/5_background/layers/3_third_layer/cemetary_thirdlayer_night_02.png', -1706, 0),
        new BackgroundObject('../img2/5_background/layers/2_second_layer/cemetary_secondlayer_night_02.png', -1706, 0),
        new BackgroundObject('../img2/5_background/layers/1_first_layer/cemetary_firstlayer_night_02.png', -1706, 0),
        new BackgroundObject('../img2/5_background/layers/cemetary_background_night_02.png', -853, 0),
        new BackgroundObject('../img2/5_background/layers/3_third_layer/cemetary_thirdlayer_night_02.png', -853, 0),
        new BackgroundObject('../img2/5_background/layers/2_second_layer/cemetary_secondlayer_night_02.png', -853, 0),
        new BackgroundObject('../img2/5_background/layers/1_first_layer/cemetary_firstlayer_night_02.png', -853, 0),
        new BackgroundObject('../img2/5_background/layers/cemetary_background_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/3_third_layer/cemetary_thirdlayer_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/2_second_layer/cemetary_secondlayer_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/1_first_layer/cemetary_firstlayer_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/cemetary_background_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/3_third_layer/cemetary_thirdlayer_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/2_second_layer/cemetary_secondlayer_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/1_first_layer/cemetary_firstlayer_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/cemetary_background_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/3_third_layer/cemetary_thirdlayer_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/2_second_layer/cemetary_secondlayer_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/1_first_layer/cemetary_firstlayer_night.png', 0, 0),
        new BackgroundObject('../img2/5_background/layers/cemetary_background_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/3_third_layer/cemetary_thirdlayer_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/2_second_layer/cemetary_secondlayer_night_02.png', 853, 0),
        new BackgroundObject('../img2/5_background/layers/1_first_layer/cemetary_firstlayer_night_02.png', 853, 0),
    ],
);